### ISSUE TITLE
python -m clip_server timeout

### ISSUE THREAD

**Issue by big-thousand** [jina-ai/clip-as-service#835]
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/114633619/192977312-d4852194-2a8f-40a5-89ba-149da6e7f600.png">

```
jtype: Flow
version: '1'
with:
  port: 51000
  #monitoring: True
  #port_monitoring: 9090
executors:
  - name: clip_t
    uses:
      jtype: CLIPEncoder
      with:
        #device: cpu
        name: M-CLIP/XLM-Roberta-Large-Vit-L-14
      metas:
        py_modules:
          - clip_server.executors.clip_torch
```
