### ISSUE TITLE
Running Docker image with customized yaml doesnt work

### ISSUE THREAD

**Issue by pasa13142** [jina-ai/clip-as-service#893]
Hi, Thanks for this great repo!

If i try to run clip as service in docker with 
`docker run -p 51009:51000 -v $HOME/.cache:/home/cas/.cache --gpus all jinaai/clip-server:master-onnx` everything is okay. It works on gpu with 1 replica.

I just would like to  run this proper docker with more replicas and created custom yaml:
`python -m clip_server onnx-flow-custom.yml` 
and tried:
`cat  onnx-flow-custom.yml | docker run -i -p 51009:51000 -v $HOME/.cache:/home/cas/.cache --gpus all jinaai/clip-server:master-onnx -i` 

and i just want to add more replicas in it instead of 1. 

```

jtype: Flow
version: '1'
with:
  port: 51000
executors:
  - name: clip_t
    replicas: 4
    uses:
      jtype: CLIPEncoder
      with: 
        device: cuda
      metas:
        py_modules:
          - clip_server.executors.clip_onnx
```

But I try with above yaml or even with original yamls like: 
```
jtype: Flow
version: '1'
with:
  port: 51000
executors:
  - name: clip_o
    uses:
      jtype: CLIPEncoder
      metas:
        py_modules:
          - clip_server.executors.clip_onnx
    timeout_ready: 3000000
    replicas: 1

```
they dont work. no gpu, no even replicas. Whatever i do, it throws that warning message with a full of page of it: Default docker image run command doesnt throw this deprecationWarning message.

```
DeprecationWarning: tostring() is deprecated. Use tobytes() instead. (raised from /usr/local/lib/python3.8/dist-packages/onnxconverter_common/float16.py:95)
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead (raised from /usr/local/lib/python3.8/dist-packages/onnxconverter_common/float16.py:91)

```
I just wanted to use original master-onnx image with more replicas. Can anyone help?
